// 种子脚本入口——调用 src/db/seed.ts
// 使用方式：pnpm seed（package.json 已配置 tsx scripts/seed.ts）
// 前置条件：DATABASE_URL 已配置（Phase 2+ 才运行）

import { randomBytes } from "crypto";
import { writeFileSync, readFileSync, existsSync } from "fs";
import { resolve } from "path";
import { config } from "dotenv";
config({ path: ".env.local" });

import { seed } from "../src/db/seed";

// 确保 iron-session 密钥存在（用于管理员 cookie 加密）
function ensureSessionSecret() {
  const envPath = resolve(process.cwd(), ".env.local");

  let content = "";
  if (existsSync(envPath)) {
    content = readFileSync(envPath, "utf-8");
  }

  if (content.includes("ADMIN_SESSION_SECRET=")) {
    console.log("ADMIN_SESSION_SECRET already set, skipping.");
    return;
  }

  const secret = randomBytes(32).toString("hex");
  const line =
    "\n# Auto-generated by pnpm seed — required for admin authentication\nADMIN_SESSION_SECRET=" +
    secret +
    "\n";
  writeFileSync(envPath, content + line, "utf-8");
  console.log("Generated ADMIN_SESSION_SECRET → .env.local");
}

ensureSessionSecret();

seed()
  .then(() => {
    console.log("种子脚本执行完成");
    process.exit(0);
  })
  .catch((err) => {
    console.error("种子脚本执行失败:", err);
    process.exit(1);
  });
